### ISSUE TITLE
Access is denied to all users.

### ISSUE THREAD

**Issue by cnr91** [vsemionov/django-blacklist#11]
In the production environment, the guest user's IP address is detected as 127.0.0.1. 
Therefore, access to the site is closed to all users. How can I block the guest user's IP address?

<img width="751" alt="image" src="https://user-images.githubusercontent.com/75105673/234888899-c9b8e966-99e0-41d0-89d7-cb20d5cddf1a.png">

**Comment by cnr91** [comment]
I used this, it solved the problem, but this is not my real ip address, it's an ip address that I don't know what it is.

In Setting:
BLACKLIST_ADDRESS_SOURCE="HTTP_X_REAL_IP"

**Comment by cnr91** [comment]
```

 from ipware import get_client_ip
client_ip, is_routable = get_client_ip(request)
```

As far as I understand, I need to use Django-ipware.
How do we use the ip address here?

**Comment by vsemionov** [comment]
Hi, sorry for my delayed response. When your application server is behind a proxy, Django and django-blacklist will "see" the proxy's IP address, instead of the client's address. It's a common case for production servers and is documented in the `Proxies and Client Addresses` section of the readme. I have not included code snippets, because the actual client address retrieval is dependent on the infrastructure and use case, and is outside this project's scope. But as an example, you can just configure django-blacklist to use a custom function to obtain the client address.

In `settings.py`:
```python
BLACKLIST_ADDRESS_SOURCE = 'your.package.get_client_address'

NUM_PROXIES = 1
```

And in your application:
```python
# this code is not tested, use it at your own risk

from django.conf import settings

def get_client_address(request):
    num_proxies = getattr(settings, 'NUM_PROXIES', 0)

    if num_proxies:
        xff = request.META['HTTP_X_FORWARDED_FOR']
        addrs = xff.split(',')
        client_addr = addrs[-min(num_proxies, len(addrs))].strip()

    else:
        client_addr = request.META['REMOTE_ADDR']

    return client_addr
```

Alternatively, you can install a custom middleware that simply replaces `request.META['REMOTE_ADDR']` with the client's IP. This would make all code in your application "see" the client address.

For a more flexible solution, I would use `django-ipware`.
